name: Release Binary on Tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and Upload Release Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: cargo build --release

      - name: Prepare binary for upload
        run: |
          cp target/release/${{ github.event.repository.name }} ${{ github.event.repository.name }}-linux-amd64

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: ${{ github.event.repository.name }}-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
